name: GitHub Actions Demo
on: [ push ]
jobs:
runs-on: ubuntu-latest
steps:
  - run: echo "The job was automatically triggered by a ${{github.event_name}} event."
  - run: javaScript Challenge1_SumOf NumbersInAnArray.js